"use client";

import { ArrowUpRight, BookOpenCheck, GraduationCap, TrendingUp } from "lucide-react";
import { useAuth } from "../../../components/auth-context";
import { PortalShell } from "../../../components/site-shell";

const courseGaps = [{ course: "BAMS · Year 3", gap: 28, priority: "Clinical documentation" }, { course: "BNYS · Year 4", gap: 19, priority: "Community facilitation" }, { course: "B.Pharm · Year 2", gap: 14, priority: "Digital health records" }];

export default function InstitutionDashboard() {
  const { user } = useAuth();
  return <PortalShell><div className="min-h-screen px-5 py-8 sm:px-8 lg:px-12"><header><p className="eyebrow">Institution workspace</p><h1 className="mt-2 font-serif text-4xl tracking-[-.04em] sm:text-5xl">{user?.name || "Institution"} programme intelligence</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/55">Translate student evidence into curriculum action with cohort-level Skill-Gap Analysis and placement reporting.</p></header><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={<GraduationCap size={18} />} label="Active learners" value="1,248" detail="Across 6 programmes" /><Metric icon={<TrendingUp size={18} />} label="Application conversion" value="34%" detail="+8 points this term" /><Metric icon={<BookOpenCheck size={18} />} label="Placement rate" value="72%" detail="Cohort 2025-26" /></div><section className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="border border-ink/10 bg-paper p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Cohort diagnostics</p><h2 className="mt-2 text-xl font-semibold">Priority skill gaps by course</h2></div><button aria-label="Open full course report" className="text-leaf"><ArrowUpRight size={18} /></button></div><div className="mt-7 space-y-6">{courseGaps.map((item) => <div key={item.course}><div className="flex justify-between gap-4 text-sm"><span className="font-semibold">{item.course}</span><span className="text-ink/50">{item.gap}% gap</span></div><div className="mt-2 h-3 bg-ink/10"><div className="h-full bg-saffron" style={{ width: `${item.gap * 2.5}%` }} /></div><p className="mt-2 text-xs text-ink/50">Priority: {item.priority}</p></div>)}</div></div><div className="bg-ink p-6 text-paper"><p className="eyebrow text-moss">Action signal</p><h2 className="mt-3 font-serif text-3xl">Add workplace documentation to the next term map.</h2><p className="mt-4 text-sm leading-6 text-paper/60">This competency appears in 68% of unfilled opportunity requirements across your active employer network.</p><button className="mt-8 flex items-center gap-2 text-sm font-bold text-saffron">Open curriculum map <ArrowUpRight size={15} /></button></div></section></div></PortalShell>;
}

function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <div className="border border-ink/10 bg-paper p-5"><span className="grid h-9 w-9 place-items-center bg-[#e6f0eb] text-leaf">{icon}</span><p className="mt-6 text-sm text-ink/50">{label}</p><p className="mt-1 font-serif text-4xl">{value}</p><p className="mt-1 text-xs text-leaf">{detail}</p></div>; }
