"use client";

import Link from "next/link";
import { BriefcaseBusiness, Plus, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { getOpportunities, Opportunity } from "../../../lib/api";
import { PortalShell } from "../../../components/site-shell";

export default function EmployerDashboard() { const [opportunities, setOpportunities] = useState<Opportunity[]>([]); const [error, setError] = useState(""); useEffect(() => { getOpportunities().then((data) => setOpportunities(data.opportunities)).catch((reason: Error) => setError(reason.message)); }, []); return <PortalShell><div className="min-h-screen px-5 py-8 sm:px-8 lg:px-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Employer workspace</p><h1 className="mt-2 font-serif text-4xl tracking-[-.04em] sm:text-5xl">Talent pipeline</h1><p className="mt-3 text-sm text-ink/55">Manage open opportunities and review evidence-led candidates.</p></div><Link href="/dashboard/employer/opportunities/new" className="flex items-center gap-2 bg-ink px-4 py-3 text-sm font-bold text-paper"><Plus size={16} />Post opportunity</Link></div>{error && <p className="mt-5 text-sm text-coral">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={<BriefcaseBusiness size={18} />} label="Open postings" value={String(opportunities.filter((item) => item.status === "open").length)} /><Metric icon={<UsersRound size={18} />} label="Active disciplines" value={String(new Set(opportunities.flatMap((item) => item.disciplines || [])).size)} /><Metric icon={<BriefcaseBusiness size={18} />} label="Published roles" value={String(opportunities.length)} /></div><section className="mt-6 border border-ink/10 bg-paper p-6"><p className="eyebrow">Your opportunities</p><div className="mt-5 space-y-3">{opportunities.map((item) => <Link key={item._id} href={`/dashboard/employer/opportunities/${item._id}/applicants`} className="flex items-center justify-between border-b border-ink/10 pb-4"><span><strong>{item.title}</strong><small className="mt-1 block text-xs text-ink/50">{item.type} · {(item.disciplines || []).join(", ")}</small></span><span className="text-xs font-bold text-leaf">Review applicants</span></Link>)}{!opportunities.length && <p className="text-sm text-ink/50">No opportunities yet.</p>}</div></section></div></PortalShell>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="border border-ink/10 bg-paper p-5"><span className="text-leaf">{icon}</span><p className="mt-5 text-sm text-ink/50">{label}</p><p className="mt-1 font-serif text-4xl">{value}</p></div>; }
