"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { apiOrigin, getPublicProfile, ProfileEvidence, ProfileSkill } from "../../../lib/api";

export default function PublicPassport({ params }: { params: { passportId: string } }) {
  const [profile, setProfile] = useState<{ name?: string; disciplines?: string[]; location?: string; skills: ProfileSkill[]; evidence: ProfileEvidence[] }>();
  const [error, setError] = useState("");
  useEffect(() => { getPublicProfile(params.passportId).then((data) => setProfile(data.profile)).catch((reason: Error) => setError(reason.message)); }, [params.passportId]);
  const publicUrl = typeof window !== "undefined" ? window.location.href : `/passport/${params.passportId}`;
  return <main className="min-h-[calc(100vh-128px)] bg-[#eef3f5] px-5 py-14 lg:px-10"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-semibold text-ink/55 hover:text-leaf">AYUSH SkillSync / public passport</Link>{error ? <p role="alert" className="mt-8 border border-coral/30 bg-coral/10 p-4 text-sm text-coral">{error}</p> : !profile ? <p className="mt-8 text-sm text-ink/50">Loading verified passport...</p> : <section className="mt-8 overflow-hidden rounded-2xl border border-ink/10 bg-paper shadow-[0_14px_40px_rgba(16,42,67,0.08)]"><div className="grid gap-8 bg-ink p-7 text-paper sm:grid-cols-[1fr_auto] sm:p-10"><div><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="text-saffron" size={18} /> Verified digital skill passport</div><h1 className="mt-14 font-serif text-5xl tracking-[-.05em]">{profile.name || "AYUSH practitioner"}</h1><p className="mt-2 text-paper/55">{profile.disciplines?.join(" & ") || "AYUSH"}{profile.location ? ` · ${profile.location}` : ""}</p></div><div className="rounded-xl bg-paper p-3"><QRCodeSVG value={publicUrl} size={126} fgColor="#102a43" bgColor="#ffffff" /></div></div><div className="p-7 sm:p-10"><div className="flex items-center justify-between border-b border-ink/10 pb-5"><div><p className="eyebrow">Verified capabilities</p><p className="mt-1 text-sm text-ink/50">Evidence-backed skills</p></div><span className="rounded-full bg-[#e6f0eb] px-3 py-1.5 text-xs font-bold text-leaf">{profile.evidence.length} signals verified</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{profile.skills.map((skill) => { const taxonomy = typeof skill.skillId === "string" ? null : skill.skillId; return <div key={`${taxonomy?._id || skill.skillId}`} className="flex items-center gap-3 rounded-lg border border-ink/10 p-4 text-sm"><CheckCircle2 size={17} className="shrink-0 text-leaf" /><span>{taxonomy?.skillNode || "AYUSH skill"}<small className="block text-xs text-ink/45">{taxonomy?.discipline || "AYUSH"} · {skill.proficiency}% proficiency</small></span></div>; })}</div><div className="mt-8 border-t border-ink/10 pt-6"><p className="eyebrow">Verified evidence</p><div className="mt-3 space-y-3">{profile.evidence.map((item) => <div key={item._id} className="flex items-center justify-between border-b border-ink/10 pb-3 text-sm"><span>{item.title}<small className="block text-xs text-ink/45">{item.issuer || "Verified submission"}</small></span>{item.fileUrl && <a href={`${apiOrigin}${item.fileUrl}`} target="_blank" rel="noreferrer" className="text-leaf" aria-label={`Open evidence for ${item.title}`}><ExternalLink size={16} /></a>}</div>)}</div></div><div className="mt-8 flex items-center justify-between border-t border-ink/10 pt-6 text-xs text-ink/45"><span>Passport ID · {params.passportId}</span><span className="flex items-center gap-1 text-leaf"><ShieldCheck size={13} />Live verification</span></div></div></section>}</div></main>;
}