import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";

export async function generateMetadata({ params }: { params: { passportId: string } }): Promise<Metadata> {
  return { title: "Arjun Mehta | Public Skill Passport", description: "A verifiable AYUSH competency profile shared through Nadi.", openGraph: { title: "Arjun Mehta · AYUSH Skill Passport", description: "View verified competencies and evidence signals on Nadi.", type: "profile", url: `/passport/${params.passportId}` }, twitter: { card: "summary_large_image", title: "AYUSH Skill Passport | Nadi", description: "A verifiable digital skill passport." } };
}

export default function PublicPassport({ params }: { params: { passportId: string } }) { return <main className="min-h-[calc(100vh-128px)] bg-[#eef3f5] px-5 py-14 lg:px-10"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-semibold text-ink/55 hover:text-leaf">nadi / public passport</Link><section className="mt-8 overflow-hidden rounded-2xl border border-ink/10 bg-paper shadow-[0_14px_40px_rgba(16,42,67,0.08)]"><div className="grid gap-8 bg-ink p-7 text-paper sm:grid-cols-[1fr_auto] sm:p-10"><div><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="text-saffron" size={18} /> Verified digital skill passport</div><h1 className="mt-14 font-serif text-5xl tracking-[-.05em]">Arjun Mehta</h1><p className="mt-2 text-paper/55">AYUSH practitioner · Ayurveda & Yoga · New Delhi</p></div><div className="rounded-xl bg-paper p-3"><QRCodeSVG value={`https://nadi.ayush.in/passport/${params.passportId}`} size={126} fgColor="#102a43" bgColor="#ffffff" /></div></div><div className="p-7 sm:p-10"><div className="flex items-center justify-between border-b border-ink/10 pb-5"><div><p className="eyebrow">Verified capabilities</p><p className="mt-1 text-sm text-ink/50">Last reviewed 09 September 2026</p></div><span className="rounded-full bg-[#e6f0eb] px-3 py-1.5 text-xs font-bold text-leaf">3 signals verified</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Clinical reasoning · Advanced", "Dravyaguna Vijnana · Intermediate", "Community facilitation · Intermediate", "Research methods · Emerging"].map((skill) => <div key={skill} className="flex items-center gap-3 rounded-lg border border-ink/10 p-4 text-sm"><CheckCircle2 size={17} className="shrink-0 text-leaf" />{skill}</div>)}</div><div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-ink/10 pt-6 text-xs text-ink/45"><span>Passport ID · {params.passportId}</span><span className="flex items-center gap-1 text-leaf"><ExternalLink size={13} />Issued by Nadi</span></div></div></section></div></main>; }
