import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CheckCircle2, MapPin } from "lucide-react";
import { ScoreBar } from "../../../components/score-bar";

const opportunity = { name: "Clinical Research Fellow", organisation: "Dhanvantari Institute of Integrative Health", location: "Pune, Maharashtra", domain: "Ayurveda", description: "Work alongside clinicians and researchers to document evidence-led approaches to integrative care.", breakdown: { skillFit: 96, domainFit: 92, locationFit: 88 } };

export async function generateMetadata({ params }: { params: { opportunityId: string } }): Promise<Metadata> {
  return { title: `${opportunity.name} | AYUSH SkillSync`, description: opportunity.description, openGraph: { title: `${opportunity.name} at ${opportunity.organisation}`, description: opportunity.description, type: "article", url: `/match/${params.opportunityId}` }, twitter: { card: "summary_large_image", title: `${opportunity.name} | AYUSH SkillSync`, description: opportunity.description } };
}

export default function OpportunityDetail() {
  return <main className="mx-auto max-w-5xl px-5 py-12 lg:px-10"><Link href="/match" className="inline-flex items-center gap-2 text-sm font-semibold text-ink/55 hover:text-leaf"><ArrowLeft size={16} /> Back to opportunities</Link><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_340px]"><section><div className="flex items-center gap-3"><span className="grid h-14 w-14 place-items-center rounded-xl bg-moss text-xl font-serif text-ink">Ay</span><div><p className="eyebrow">{opportunity.domain} · Internship</p><h1 className="mt-1 font-serif text-4xl tracking-[-.04em]">{opportunity.name}</h1></div></div><p className="mt-8 max-w-2xl text-lg leading-8 text-ink/65">{opportunity.description}</p><div className="mt-8 flex items-center gap-2 text-sm text-ink/50"><MapPin size={16} className="text-leaf" />{opportunity.location}<span className="mx-2">·</span>{opportunity.organisation}</div><div className="mt-12 border-t border-ink/10 pt-8"><h2 className="text-xl font-semibold">What you will work on</h2><ul className="mt-5 space-y-3 text-sm leading-6 text-ink/65"><li className="flex gap-3"><CheckCircle2 size={18} className="mt-1 shrink-0 text-leaf" />Support clinical documentation and structured case research.</li><li className="flex gap-3"><CheckCircle2 size={18} className="mt-1 shrink-0 text-leaf" />Translate practice observations into evidence-ready insights.</li><li className="flex gap-3"><CheckCircle2 size={18} className="mt-1 shrink-0 text-leaf" />Collaborate with an interdisciplinary AYUSH research team.</li></ul></div></section><aside className="paper-panel h-fit rounded-xl p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">Your match</p><p className="mt-1 font-serif text-5xl text-leaf">94<span className="text-base text-ink/40"> / 100</span></p></div><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e6f0eb] text-leaf"><CheckCircle2 size={19} /></span></div><p className="mt-5 text-sm leading-6 text-ink/55">A transparent score based on your current verified profile.</p><div className="mt-6 space-y-4"><ScoreBar label="Skill fit" value={opportunity.breakdown.skillFit} /><ScoreBar label="Domain fit" value={opportunity.breakdown.domainFit} color="bg-saffron" /><ScoreBar label="Location fit" value={opportunity.breakdown.locationFit} color="bg-coral" /></div><button className="mt-7 flex w-full items-center justify-center gap-2 rounded-lg bg-ink py-3 text-sm font-bold text-paper hover:bg-leaf">Start application <ArrowUpRight size={16} /></button></aside></div></main>;
}
