"use client";

import Link from "next/link";
import { ArrowUpRight, MapPin, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { PortalShell } from "../../components/site-shell";

const opportunities = [
  { id: "clinical-research-fellow", title: "Clinical Research Fellow", organisation: "Dhanvantari Institute of Integrative Health", location: "Pune, Maharashtra", type: "Internship", score: 94, skills: ["Dravyaguna", "Clinical reasoning", "Research methods"], breakdown: { skill: 96, domain: 92, eligibility: 100, location: 88, availability: 94 } },
  { id: "community-yoga-facilitator", title: "Community Yoga Facilitator", organisation: "Svastha Foundation", location: "Remote · India", type: "Fellowship", score: 88, skills: ["Asana practice", "Community care", "Teaching"], breakdown: { skill: 84, domain: 96, eligibility: 90, location: 100, availability: 78 } },
  { id: "digital-ayurveda-associate", title: "Digital Ayurveda Associate", organisation: "Arogya Labs", location: "Bengaluru, Karnataka", type: "Part-time", score: 81, skills: ["Ayurvedic nutrition", "Content", "Patient journeys"], breakdown: { skill: 78, domain: 90, eligibility: 84, location: 74, availability: 76 } },
];

const factors = [{ key: "skill", label: "Skill compatibility", weight: "40%" }, { key: "domain", label: "Domain fit", weight: "20%" }, { key: "eligibility", label: "Eligibility", weight: "15%" }, { key: "location", label: "Preference / location", weight: "15%" }, { key: "availability", label: "Availability", weight: "10%" }] as const;

export default function MatchPage() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => opportunities.filter((item) => `${item.title} ${item.organisation}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <PortalShell><div className="min-h-screen px-5 py-8 sm:px-8 lg:px-12"><header><p className="eyebrow">Explainable recommendations</p><h1 className="mt-2 font-serif text-4xl tracking-[-.04em] sm:text-5xl">Opportunity matches</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/55">Every score is a weighted summary of your evidence, preferences, and readiness. There is no black-box decision.</p></header><section className="mt-8 border border-ink/10 bg-ink p-5 text-paper sm:p-7"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-moss">Scoring model M</p><h2 className="mt-2 font-serif text-3xl">Skill-Gap Analysis in context</h2></div><div className="grid grid-cols-2 gap-x-7 gap-y-3 text-xs text-paper/65 sm:grid-cols-5">{factors.map((factor) => <div key={factor.key}><strong className="block text-xl text-saffron">{factor.weight}</strong>{factor.label}</div>)}</div></div></section><label className="relative mt-8 block"><span className="sr-only">Search opportunities</span><Search size={17} className="absolute left-4 top-3.5 text-ink/35" aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by role or organisation" className="w-full border border-ink/10 bg-paper py-3 pl-11 pr-4 text-sm outline-none focus:border-leaf" /></label><div className="mt-6 space-y-4">{filtered.map((item) => <article key={item.id} className="border border-ink/10 bg-paper p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{item.type} · {item.organisation}</p><h2 className="mt-2 text-2xl font-semibold">{item.title}</h2><p className="mt-2 flex items-center gap-2 text-sm text-ink/50"><MapPin size={15} className="text-leaf" />{item.location}</p></div><div className="text-right"><p className="eyebrow">Explainable Match Score</p><p className="mt-1 font-serif text-5xl text-leaf">{item.score}<span className="text-base text-ink/35"> / 100</span></p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{factors.map((factor) => <div key={factor.key}><div className="flex justify-between text-[11px] font-semibold text-ink/55"><span>{factor.label}</span><span>{item.breakdown[factor.key]}</span></div><div className="mt-2 h-2 bg-ink/10"><div className="h-full bg-leaf" style={{ width: `${item.breakdown[factor.key]}%` }} /></div></div>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-2">{item.skills.map((skill) => <span key={skill} className="border border-ink/10 px-2.5 py-1 text-xs text-ink/60">{skill}</span>)}</div><Link href={`/match/${item.id}`} className="flex items-center gap-2 text-sm font-bold text-leaf hover:text-ink">Review evidence <ArrowUpRight size={16} /></Link></div></article>)}</div></div></PortalShell>;
}
